[package]
name = "vk"
version = "0.1.0"
edition = "2024"
license = "ISC"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json", "rustls-tls"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
termimad = "0.33.0"
thiserror = "1.0.57"
url = "2.5.0"
regex = "1.10.3"
diffy = "0.4.2"
chrono = { version = "0.4", features = ["serde", "clock"] }
anyhow = "1.0"
ortho_config = { git = "https://github.com/leynos/ortho-config", tag = "v0.2.0", default-features = false }
figment = { version = "0.10", default-features = false, features = ["env", "toml"], optional = true }
xdg = { version = "3", optional = true }
uncased = { version = "0.9", optional = true }
toml = { version = "0.8", optional = true }

[features]
default = ["toml"]
toml = ["dep:figment", "dep:xdg", "dep:uncased", "dep:toml", "ortho_config/toml"]
json5 = ["toml", "ortho_config/json5"]
yaml = ["toml", "ortho_config/yaml"]

[dev-dependencies]
tempfile = "3.20.0"
serial_test = "3.2.0"
rstest = "0.25.0"

[lints.clippy]
# make every pedantic lint emit a warning
pedantic = "warn"
