[package]
name = "vk"
version = "0.1.0"
edition = "2024"
license = "ISC"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json", "rustls-tls"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
termimad = "0.33.0"
thiserror = "1.0.57"
url = "2.5.0"
regex = "1.10.3"
diffy = "0.4.2"
anyhow = "1.0"
ortho_config = { git = "https://github.com/leynos/ortho-config", tag = "v0.2.0" }
figment = { version = "0.10", default-features = false, features = ["env", "toml"] }
xdg = "3"
uncased = "0.9"
toml = "0.8"

[features]
default = ["toml"]
toml = []
json5 = []
yaml = []

[dev-dependencies]
tempfile = "3.20.0"
serial_test = "3.2.0"

[lints.clippy]
# make every pedantic lint emit a warning
pedantic = "warn"
