[package]
name = "vk"
version = "0.1.0"
edition = "2024"
license = "ISC"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json", "rustls-tls"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
termimad = "0.33.0"
thiserror = "1.0.57"
url = "2.5.0"
regex = "1.10.3"
once_cell = "1.19.0"
