[package]
name = "vk"
version = "0.1.0"
edition = "2024"
license = "ISC"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json", "rustls-tls"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
termimad = "0.33.0"
thiserror = "1.0.57"
url = "2.5.0"
regex = "1.10.3"
diffy = "0.4.2"
anyhow = "1.0"
ortho_config = { git = "https://github.com/leynos/ortho-config", tag = "v0.2.0", default-features = false }
figment = { version = "0.10", default-features = false, features = ["env", "toml"], optional = true }
xdg = { version = "3", optional = true }
uncased = { version = "0.9", optional = true }
toml = { version = "0.8", optional = true }

[features]
default = ["toml"]
toml = ["dep:figment", "dep:xdg", "dep:uncased", "dep:toml", "ortho_config/toml"]
json5 = ["toml", "ortho_config/json5"]
yaml = ["toml", "ortho_config/yaml"]

[dev-dependencies]
tempfile = "3.20.0"
serial_test = "3.2.0"
rstest = "0.25.0"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }

# 1. hygiene
# Unfortunately, due to an 'unused-braces' false postive with
# single line rstest fixtures, and the fact that fixtures do
# not permit 'expect' attributes, we must disable this deny.
# allow_attributes                    = "deny"
allow_attributes_without_reason     = "deny"
blanket_clippy_restriction_lints    = "deny"

# 2. debugging leftovers
# Disabled pending further investigation into applicability.
# dbg_macro       = "deny"
# print_stdout    = "deny"
# print_stderr    = "deny"

# 3. panic-prone operations
unwrap_used                     = "deny"
# Expect used in tests. Discoraged in implementation code.
# expect_used                     = "deny"
indexing_slicing                = "deny"
string_slice                    = "deny"
integer_division                = "deny"
integer_division_remainder_used = "deny"

# 4. portability
host_endian_bytes   = "deny"
little_endian_bytes = "deny"
big_endian_bytes    = "deny"

# 5. nursery idiom polish
or_fun_call            = "deny"
option_if_let_else     = "deny"
use_self               = "deny"
string_lit_as_bytes    = "deny"

# 6. numerical foot-guns
float_arithmetic = "deny"
