//! GraphQL helpers for resolving review comment threads.
//!
//! The thread lookup pages through `repository.pullRequest.reviewThreads`,
//! scanning each thread's first 100 comments for the requested comment's
//! database id (`fullDatabaseId`; the plain `databaseId` field is deprecated
//! in the schema). An earlier revision paged a flat
//! `PullRequest.reviewComments` connection, but that field does not exist in
//! GitHub's published GraphQL schema — it only ever worked against mocked
//! responses — so the query was redesigned onto the real schema when the
//! operations moved to `graphql_client` codegen.
//!
//! Accepted limitation: a comment beyond the first 100 comments of a single
//! thread will not be found (the per-thread `comments(first: 100)` cap). This
//! is the same class of cap as the old flat query's `first: 100` page size;
//! review threads of that depth are not a practical concern for `vk resolve`.

use super::CommentRef;
// `graphql_client` resolves the `BigInt` scalar (`fullDatabaseId`) to a type
// of the same name in scope of the derive; the shared alias supplies it.
use crate::api::scalars::BigInt;
use crate::{VkError, api::GraphQLClient};
use graphql_client::GraphQLQuery;

/// Typed `ThreadForCommentQuery` operation: pages review threads (with their
/// first 100 comments) so [`get_thread_id`] can locate the thread owning a
/// comment database id.
///
/// Uses the generated `ResponseData` directly: the fetcher trait below is the
/// only consumer, its unit tests construct the generated types via [`tests`]
/// helpers, and the integration stubs supply every selected field.
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "graphql/schema.docs.graphql",
    query_path = "graphql/resolve.graphql",
    response_derives = "Debug, Clone, PartialEq"
)]
pub(crate) struct ThreadForCommentQuery;

/// Typed `ResolveReviewThreadMutation`: marks a review thread resolved.
///
/// Uses the generated `ResponseData` directly ([`GraphQLClient::run_operation`])
/// since nothing beyond a successful deserialization is consumed.
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "graphql/schema.docs.graphql",
    query_path = "graphql/resolve.graphql",
    response_derives = "Debug, Clone, PartialEq"
)]
pub(crate) struct ResolveReviewThreadMutation;

/// One page of thread-for-comment data as returned by the API.
pub(crate) type ThreadPage = thread_for_comment_query::ResponseData;
/// Generated review-thread connection used during thread lookup.
type ReviewThreads =
    thread_for_comment_query::ThreadForCommentQueryRepositoryPullRequestReviewThreads;
/// Generated pagination metadata for a review-thread connection.
type ReviewThreadsPageInfo =
    thread_for_comment_query::ThreadForCommentQueryRepositoryPullRequestReviewThreadsPageInfo;

#[cfg(test)]
use mockall::automock;

/// Parameters for one review-thread page request.
#[derive(Debug)]
pub(crate) struct ReviewCommentsQuery<'a> {
    /// Repository owner login.
    pub owner: &'a str,
    /// Repository name.
    pub name: &'a str,
    /// Pull request number.
    pub number: u64,
    /// Cursor after which to fetch the next page.
    pub after: Option<String>,
}

/// Fetches codegen response pages for review-comment thread lookup.
#[cfg_attr(test, automock)]
#[allow(clippy::ref_option, reason = "automock generates &Option")]
pub(crate) trait ReviewCommentsFetcher {
    /// Fetch one page of review threads and their initial comments.
    #[expect(
        clippy::elidable_lifetime_names,
        reason = "automock requires explicit lifetime for query struct"
    )]
    async fn fetch_review_comments<'a>(
        &self,
        query: ReviewCommentsQuery<'a>,
    ) -> Result<ThreadPage, VkError>;
}

impl ReviewCommentsFetcher for GraphQLClient {
    #[expect(
        clippy::elidable_lifetime_names,
        reason = "automock requires explicit lifetime for query struct"
    )]
    async fn fetch_review_comments<'a>(
        &self,
        query: ReviewCommentsQuery<'a>,
    ) -> Result<ThreadPage, VkError> {
        // GraphQL `Int` is signed 32-bit, so validate that range before
        // widening to the `i64` representation generated by graphql_client.
        let number = i64::from(i32::try_from(query.number).map_err(|_| VkError::InvalidNumber)?);
        let variables = thread_for_comment_query::Variables {
            owner: query.owner.to_string(),
            name: query.name.to_string(),
            number,
            after: query.after,
        };
        self.run_operation::<ThreadForCommentQuery>(variables).await
    }
}

/// Scan one page of review threads for the comment with `target` database id,
/// returning the owning thread's id when found.
fn find_thread_in_page(
    threads: Vec<
        Option<
            thread_for_comment_query::ThreadForCommentQueryRepositoryPullRequestReviewThreadsNodes,
        >,
    >,
    target: &str,
) -> (Option<String>, bool) {
    let mut comments_truncated = false;
    for thread in threads.into_iter().flatten() {
        let hit = thread
            .comments
            .nodes
            .iter()
            .flatten()
            .flatten()
            .any(|comment| comment.full_database_id.as_deref() == Some(target));
        if hit {
            return (Some(thread.id), comments_truncated);
        }
        comments_truncated |= thread.comments.page_info.has_next_page;
    }
    (None, comments_truncated)
}

/// Extract review threads from a GraphQL response page.
fn review_threads_from_page(data: ThreadPage) -> Result<ReviewThreads, VkError> {
    data.repository
        .and_then(|repository| repository.pull_request)
        .map(|pull_request| pull_request.review_threads)
        .ok_or_else(|| VkError::BadResponse("missing review threads".into()))
}

/// Return the cursor for the next review-thread page, if one exists.
#[expect(
    clippy::ref_option,
    reason = "the extraction contract retains the caller's cursor representation"
)]
fn next_thread_cursor(
    page_info: &ReviewThreadsPageInfo,
    previous: &Option<String>,
) -> Result<Option<String>, VkError> {
    if !page_info.has_next_page {
        return Ok(None);
    }
    let next = page_info
        .end_cursor
        .clone()
        .ok_or_else(|| VkError::BadResponse("missing endCursor with hasNextPage".into()))?;
    if previous.as_deref() == Some(next.as_str()) {
        return Err(VkError::BadResponse(
            "non-progressing pagination (repeated endCursor)".into(),
        ));
    }
    Ok(Some(next))
}

/// Return the terminal error after the review-thread traversal finishes.
fn thread_lookup_error(comment_id: u64, comments_truncated: bool) -> VkError {
    if comments_truncated {
        return VkError::BadResponse(
            format!(
                "comment {comment_id} was not found in the fetched first 100 comments of a review thread"
            )
            .into(),
        );
    }
    VkError::CommentNotFound { comment_id }
}

/// Find the review thread that owns the referenced discussion comment.
pub(crate) async fn get_thread_id(
    gql: &impl ReviewCommentsFetcher,
    reference: CommentRef<'_>,
) -> Result<String, VkError> {
    // Comment ids come from `#discussion_r<ID>` permalinks; `fullDatabaseId`
    // is a `BigInt` scalar carried as a decimal string, so the id is matched
    // by its canonical string form.
    let target = reference.comment_id.to_string();
    let mut cursor: Option<String> = None;
    let mut comments_truncated = false;
    loop {
        let data = gql
            .fetch_review_comments(ReviewCommentsQuery {
                owner: &reference.repo.owner,
                name: &reference.repo.name,
                number: reference.pull_number,
                after: cursor.clone(),
            })
            .await?;
        let threads = review_threads_from_page(data)?;
        if let Some(nodes) = threads.nodes {
            let (id, page_truncated) = find_thread_in_page(nodes, &target);
            if let Some(id) = id {
                return Ok(id);
            }
            comments_truncated |= page_truncated;
        }
        let Some(next) = next_thread_cursor(&threads.page_info, &cursor)? else {
            break;
        };
        cursor = Some(next);
    }
    Err(thread_lookup_error(
        reference.comment_id,
        comments_truncated,
    ))
}

/// Mark a review thread as resolved through the typed mutation.
pub(crate) async fn resolve_thread(gql: &GraphQLClient, thread_id: &str) -> Result<(), VkError> {
    // The mutation's response is intentionally unconsumed beyond a successful
    // deserialization, so the generated `ResponseData` is discarded.
    let _ = gql
        .run_operation::<ResolveReviewThreadMutation>(resolve_review_thread_mutation::Variables {
            id: thread_id.to_string(),
        })
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests;
