query PrForBranchQuery(
  $owner: String!
  $name: String!
  $headRef: String!
  $after: String
) {
  repository(owner: $owner, name: $name) {
    pullRequests(
      headRefName: $headRef
      first: 10
      after: $after
      states: [OPEN, MERGED]
      orderBy: {field: UPDATED_AT, direction: DESC}
    ) {
      nodes {
        number
        headRepository {
          owner {
            __typename
            login
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
