query ThreadForCommentQuery($owner: String!, $name: String!, $number: Int!, $after: String) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      reviewThreads(first: 100, after: $after) {
        pageInfo {
          endCursor
          hasNextPage
        }
        nodes {
          id
          comments(first: 100) {
            nodes {
              fullDatabaseId
            }
          }
        }
      }
    }
  }
}

mutation ResolveReviewThreadMutation($id: ID!) {
  resolveReviewThread(input: { threadId: $id }) {
    clientMutationId
  }
}
