//! GraphQL wire adapter for single-issue retrieval.
//!
//! This submodule owns every transport-facing shape of the lookup: the
//! `#[derive(GraphQLQuery)]` operation, the generated-variable construction
//! (including the GraphQL `Int` range check), the response mapping, and the
//! call into [`GraphQLClient`]. The mapping returns the parent module's
//! [`Issue`] domain type, so no generated type escapes this submodule.

use crate::boxed::BoxedStr;
use crate::ref_parser::RepoInfo;
use crate::{GraphQLClient, VkError};
use graphql_client::GraphQLQuery;

use super::Issue;

/// Typed `IssueQuery` GraphQL operation.
///
/// Generated from `graphql/issue.graphql` and validated against the vendored
/// schema at compile time. The generated module `issue_query` provides the
/// `Variables` and `ResponseData` types consumed by [`fetch_issue`].
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "graphql/schema.docs.graphql",
    query_path = "graphql/issue.graphql",
    response_derives = "Debug, Clone, PartialEq"
)]
struct IssueQuery;

/// Convert an `IssueQuery` response into the public [`Issue`] type.
///
/// A missing `repository` or `issue` node (both nullable in the schema) means
/// the requested issue does not exist; this is surfaced as a [`VkError`] rather
/// than a panic, matching the pre-codegen behaviour where the required-field
/// deserialization failed on a null issue.
pub(super) fn issue_from_response(
    data: issue_query::ResponseData,
    number: u64,
) -> Result<Issue, VkError> {
    let issue = data
        .repository
        .and_then(|repository| repository.issue)
        .ok_or_else(|| VkError::BadResponse(format!("issue #{number} not found").boxed()))?;
    Ok(Issue {
        title: issue.title,
        body: issue.body,
    })
}

/// Build the operation variables for a validated issue number.
///
/// GraphQL `Int` is signed 32-bit, so the range is checked before widening to
/// the `i64` representation generated by `graphql_client`.
pub(super) fn issue_variables(
    repo: &RepoInfo,
    number: u64,
) -> Result<issue_query::Variables, VkError> {
    Ok(issue_query::Variables {
        owner: repo.owner.clone(),
        name: repo.name.clone(),
        number: i64::from(i32::try_from(number).map_err(|_| VkError::InvalidNumber)?),
    })
}

/// Fetch a single issue by repository and number.
pub(super) async fn fetch_issue(
    client: &GraphQLClient,
    repo: &RepoInfo,
    number: u64,
) -> Result<Issue, VkError> {
    let variables = issue_variables(repo, number)?;
    let data = client.run_operation::<IssueQuery>(variables).await?;
    issue_from_response(data, number)
}

#[cfg(test)]
mod tests {
    //! Wire-adapter tests for issue retrieval.
    //!
    //! These cover the two halves of the adapter directly: the variable
    //! construction (including the `Int` range check) and the response
    //! mapping. The end-to-end request path, including the operation name and
    //! serialized variables, is covered by [`super::super::tests`].

    use super::*;

    #[test]
    fn issue_variables_reject_an_out_of_range_number() {
        let repo = RepoInfo {
            owner: "owner".into(),
            name: "repository".into(),
        };

        let result = issue_variables(&repo, i32::MAX as u64 + 1);

        assert!(matches!(result, Err(VkError::InvalidNumber)));
    }

    #[test]
    fn issue_variables_widen_the_number_to_i64() {
        let repo = RepoInfo {
            owner: "owner".into(),
            name: "repository".into(),
        };

        let variables = issue_variables(&repo, 42).expect("in-range number");

        assert_eq!(variables.owner, "owner");
        assert_eq!(variables.name, "repository");
        assert_eq!(variables.number, 42_i64);
    }

    #[test]
    fn issue_from_response_maps_the_selected_fields() {
        let data = issue_query::ResponseData {
            repository: Some(issue_query::IssueQueryRepository {
                issue: Some(issue_query::IssueQueryRepositoryIssue {
                    title: "Issue title".into(),
                    body: "Issue body".into(),
                }),
            }),
        };

        let issue = issue_from_response(data, 42).expect("mapped issue");

        assert_eq!(
            issue,
            Issue {
                title: "Issue title".into(),
                body: "Issue body".into(),
            }
        );
    }

    #[test]
    fn issue_from_response_reports_a_missing_issue() {
        let data = issue_query::ResponseData { repository: None };

        let error = issue_from_response(data, 42).expect_err("missing issue");

        assert!(
            matches!(error, VkError::BadResponse(message) if message.as_ref() == "issue #42 not found")
        );
    }

    #[test]
    fn issue_from_response_reports_a_missing_issue_node() {
        let data = issue_query::ResponseData {
            repository: Some(issue_query::IssueQueryRepository { issue: None }),
        };

        let error = issue_from_response(data, 42).expect_err("missing issue node");

        assert!(
            matches!(error, VkError::BadResponse(message) if message.as_ref() == "issue #42 not found")
        );
    }
}
